name: NovaLib
version: ${revision}
description: An advanced API and Library for our plugins and so much more!
author: DreamExposure
authors: [NovaFox161]
website: https://www.dreamexposure.org/plugins/novalib

main: org.dreamexposure.novalib.plugin.bungee.NovaLib
