name: NovaLib
version: ${revision}
description: An advanced API and Library for our plugins and so much more!
author: DreamExposure
authors: [NovaFox161]
website: https://www.dreamexposure.org/plugins/novalib

api-version: 1.13

softdepend: [Vault]

main: org.dreamexposure.novalib.plugin.bukkit.NovaLib

permissions:
  novalib.update.notify:
    description: Allows the player to be notified when an update is available.
    default: op
